### ISSUE TITLE
划词不翻译

### ISSUE THREAD

**Issue by liwenzu** [do-something-for-fun/thesis-helper#48]
为什么最近用不了了，不翻译。

**Comment by pullself** [comment]
同问题，我的报错如下：
Exception in thread :
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "thesisUtils\watch_clip.py", line 21, in run
  File "thesisUtils\watch_clip.py", line 27, in update
  File "thesisUtils\translate.py", line 73, in get_translation_by_google
  File "site-packages\googletrans\client.py", line 172, in translate
  File "thesisUtils\translate.py", line 17, in _translate
  File "site-packages\googletrans\gtoken.py", line 200, in do
  File "site-packages\googletrans\gtoken.py", line 65, in _update
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by HRex39** [comment]
感觉应该是googletrans接口的问题

**Comment by yuhao0613** [comment]
确实，现在用不了了
